name: netflix_analytics

profile: jaffle_shop

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  netflix_analytics:
    +static_analysis: strict

    staging:
      +schema: netflix_silver
      +materialized: view

    intermediate:
      +schema: netflix_silver
      +materialized: view

    marts:
      +schema: netflix_gold
      +materialized: table
