name: netflix_analytics

profile: jaffle_shop

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  netflix_analytics:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    staging:
      +schema: netflix_silver
      +materialized: view
